export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  changes: {
    type: "feature" | "improvement" | "fix" | "security";
    description: string;
  }[];
}

export const APP_VERSION = "3.5.0";

export const changelog: ChangelogEntry[] = [
  {
    version: "3.5.0",
    date: "2026-04-23",
    title: "Truck Routes, Order Notifications, Seasonal Inventory & Hardened Security",
    changes: [
      { type: "feature", description: "Truck Routes — new admin page (Orders → Truck Routes) lets you define delivery routes with an ordered list of store stops. Each stop's notification email is shown right in the route editor so you can see exactly who'll be alerted." },
      { type: "feature", description: "Trailer manifests can now be tied to a configured truck route. When a manifest moves to In Transit, the system emails every store on the route automatically (instead of just one destination), with duplicates removed and stops missing an email skipped gracefully." },
      { type: "feature", description: "Order Fulfilled email — when the warehouse marks an equipment order as fulfilled, the requesting store and submitter are emailed automatically with a list of every item that was filled. No extra approval step; the fulfill toggle is the trigger." },
      { type: "feature", description: "Seasonal Inventory page — new dashboard (Orders → Seasonal Inventory) shows on-deposit and pending-requested seasonal counts across every store in one view, computed live from order submissions." },
      { type: "feature", description: "Configurable Truck Routes permissions — admins can now control who can view, edit, or delete truck routes independently of trailer manifest permissions. Defaults preserve existing access (admin, manager, ordering)." },
      { type: "feature", description: "Configurable Seasonal Inventory permission — the cross-store aggregate view now has its own permission key (Seasonal Inventory → View), separate from order viewing. Per-store seasonal lookups used by the Order Form remain available to all submitters." },
      { type: "improvement", description: "Truck-route stops are validated before saving — the system rejects unknown stores, removes duplicates while preserving order, and skips a database write entirely when the stop list hasn't actually changed." },
      { type: "improvement", description: "Routes that are still attached to a trailer manifest can no longer be deleted by accident — the delete is rejected with a clear message so you don't end up with broken manifest references." },
      { type: "improvement", description: "Manifest creation form now includes a route picker that auto-fills the route number and previews exactly which stores will be notified before you save." },
      { type: "security", description: "Locked down object storage — uploads now require login, and downloads enforce per-file access control so HR records, coaching attachments, manifest photos, driver inspection photos, and credit-card terminal photos can no longer be retrieved by sharing a URL." },
      { type: "security", description: "Schedule copy and template endpoints now enforce feature permissions and per-store location scoping. Non-admins can no longer copy or apply templates to stores outside their assigned locations." },
      { type: "security", description: "Global Settings API now redacts UKG credentials and notification email lists for non-admin users. Only admins receive the full settings payload." },
      { type: "security", description: "Employee detail endpoint now enforces the same role and location controls as the employee list — non-admins outside an employee's stores are blocked, and viewer-role users see redacted personal data." },
      { type: "security", description: "Production API logs no longer capture response bodies. Previously every /api response was serialized into the request log, which could expose secrets and PII to anyone with log access." },
      { type: "security", description: "Patched 13 dependency vulnerabilities (4 high, 8 moderate, 1 low) across xmldom, dompurify, fast-xml-parser, cookie, http-proxy-agent, and uuid via package overrides. Audit now reports zero vulnerabilities." },
      { type: "fix", description: "Fixed a MySQL proxy connection error that intermittently broke order submission and retrieval." },
      { type: "improvement", description: "Permission-test suite expanded to cover every truck-routes endpoint and the seasonal-inventory aggregate view, so accidental gate removals will be caught automatically going forward." },
    ],
  },
  {
    version: "3.0.4",
    date: "2026-04-21",
    title: "View As (User Impersonation)",
    changes: [
      { type: "feature", description: "Admins can now click View As on any active user in the Users page to experience the app exactly as that user does — same role, permissions, sidebar, location filters, and visibility rules. Useful for confirming what a manager or viewer can or can't see." },
      { type: "feature", description: "While viewing as another user, an amber banner appears at the top of every page identifying the impersonated user. Click Stop viewing in the banner to return to your admin session at any time." },
    ],
  },
  {
    version: "3.0.3",
    date: "2026-04-21",
    title: "Configurable Job Title Hierarchy",
    changes: [
      { type: "feature", description: "New Admin → Job Title Hierarchy page lets admins pick, for each job title, exactly which other job titles a person with that title can see in coaching and attendance. Useful for non-standard titles that don't fit the built-in District / Store Mgr / Asst Mgr / Team Lead levels." },
      { type: "improvement", description: "If a viewer's job title has a configured visibility list, that list is used instead of the built-in level rules (still scoped to the user's allowed store locations). Titles with nothing configured continue to use the built-in rules, so existing setups keep working." },
      { type: "improvement", description: "Visibility precedence is now: explicit Direct Reports on a user → per-job-title visibility map → built-in level hierarchy." },
    ],
  },
  {
    version: "3.0.2",
    date: "2026-04-21",
    title: "Manager Direct Reports",
    changes: [
      { type: "feature", description: "Admins can now assign explicit direct reports to any manager or optimizer user. Open the user menu on the Users page and choose Manage Direct Reports to pick the employees that report to them." },
      { type: "improvement", description: "When a user has any explicit direct reports assigned, those assignments fully replace the automatic job-title hierarchy for coaching and attendance visibility — useful when a manager oversees a custom group across stores." },
      { type: "improvement", description: "Users with no explicit assignments continue to use the existing job-title-based hierarchy, so nothing changes until you opt in." },
    ],
  },
  {
    version: "3.0.1",
    date: "2026-04-21",
    title: "Sidebar Reorganization, Role Renaming & Navigation Polish",
    changes: [
      { type: "feature", description: "Sidebar navigation reorganized into collapsible section groups (Scheduling, Development, Orders, Inventory, Reports, Configuration, Admin) with each section's open/closed state remembered per browser." },
      { type: "feature", description: "Configuration and Admin sections now sit at the bottom of the sidebar, keeping setup tools out of the way of day-to-day work." },
      { type: "feature", description: "Command palette — press ⌘K (Mac) or Ctrl+K (Windows) anywhere in the app to search and jump to any page, including external inventory links." },
      { type: "feature", description: "Renameable roles — admins can click the pencil icon on any role chip in Permissions to give built-in or custom roles a new display name. Internal identifiers stay intact so existing assignments keep working." },
      { type: "fix", description: "Users page now shows each user's role display name (including renamed and custom roles) instead of the raw role code." },
    ],
  },
  {
    version: "3.0.0",
    date: "2026-04-20",
    title: "Driver Inspection, Inventory Links & Login Customization",
    changes: [
      { type: "feature", description: "Driver Inspection module — pre-trip inspection form covering tires, brakes, lights, fluids, horn, mirrors, wipers, seatbelt, and more. Drivers can flag any item as needing repair, add notes, and submit for the record." },
      { type: "feature", description: "Driver Inspection list and detail pages for reviewing past inspections, filtering by driver, date, and repair status." },
      { type: "feature", description: "Automatic email alerts to a configurable distribution list whenever a driver flags an inspection item as needing repair." },
      { type: "feature", description: "Inventory navigation section with quick links to the New Goods and Supplies Showroom and Stock Count tools in inFlow Inventory." },
      { type: "feature", description: "Editable login page tagline — admins can change the message shown under the logo on the sign-in page from Settings, or leave it blank to restore the default." },
      { type: "feature", description: "Login page now displays the current application version and release date so users can confirm which build they're on." },
      { type: "improvement", description: "Settings page now groups Driver Inspection repair-alert emails and the login tagline alongside the existing HR and order notification configuration." },
    ],
  },
  {
    version: "2.0.0",
    date: "2026-04-14",
    title: "Security Hardening",
    changes: [
      { type: "security", description: "Removed logging of MySQL connection details to standard output to prevent sensitive data exposure." },
    ],
  },
  {
    version: "1.5.1",
    date: "2026-03-27",
    title: "Dual Tasks, Sound Controls & PDF Improvements",
    changes: [
      { type: "feature", description: "Dual/secondary task support: click on an existing task block to assign a second task for the same time slot. Primary tasks display in the top half and secondary tasks in the bottom half with a dashed border." },
      { type: "feature", description: "Mute toggle button added to the toolbar — click the speaker icon to silence sound effects. Preference is saved across sessions." },
      { type: "improvement", description: "PDF export now renders dual tasks with primary/secondary split layout matching the on-screen view." },
      { type: "improvement", description: "PDF rows are taller with larger text for better readability. Task legend removed to save space." },
      { type: "improvement", description: "Task creation sound replaced with a cheerful ascending chime instead of the previous laser-style tone." },
      { type: "improvement", description: "Whoosh sound now plays when deleting individual tasks, not just when clearing the whole day." },
    ],
  },
  {
    version: "1.5",
    date: "2026-03-26",
    title: "Custom Tasks",
    changes: [
      { type: "feature", description: "Users can now create their own custom tasks with a name and color via the 'Custom Task' button on the Task Assignment page." },
      { type: "feature", description: "Custom tasks are saved per user and only visible to the creator, not shared with other users." },
      { type: "feature", description: "Custom tasks appear in the task selector dropdown, bottom legend, and PDF export alongside the 14 predefined tasks." },
      { type: "feature", description: "Custom tasks can be deleted from the manage dialog without affecting predefined tasks." },
    ],
  },
  {
    version: "1.39.0",
    date: "2026-03-26",
    title: "Task Assignment Timeline",
    changes: [
      { type: "feature", description: "New Task Assignment page with an interactive day timeline view for assigning daily tasks to scheduled employees." },
      { type: "feature", description: "14 predefined tasks: Complete Pulls, Run Register, Run Rack, Process Clothes/Wares/Shoes/Accessories, Complete eCommerce, restroom cleaning, dust mop, floor machine, Stock New Goods, and Flex Assigned Clothing Racks." },
      { type: "feature", description: "Click and drag on the timeline to create task blocks, drag blocks to move, drag the right edge to resize, and Ctrl+drag to copy." },
      { type: "feature", description: "Right-click any task block to delete it. Clear Day button removes all task assignments for the selected date." },
      { type: "feature", description: "Each task has a distinct color. Employee rows show shift background and job title color indicators." },
      { type: "feature", description: "Production estimates for Apparel (APPROC/APWV) and Wares (DONPRI/DONPRWV) are displayed based on scheduled effective hours." },
      { type: "feature", description: "Export PDF button generates a landscape PDF with visual timeline, task blocks with colors, employee rows with job codes, production estimates, and a task legend." },
      { type: "feature", description: "Cross-employee drag and drop: move or copy task blocks between employees. Left and right edge resize handles." },
      { type: "feature", description: "Copy Previous Day button to bulk-copy task assignments from the previous day." },
      { type: "feature", description: "Date picker for direct date navigation (click on the date label)." },
    ],
  },
  {
    version: "1.38.0",
    date: "2026-03-26",
    title: "Cross-Trained Role Shift Notes",
    changes: [
      { type: "feature", description: "Shifts can now be marked as 'Cross-Trained Role' when an employee is performing a different role than their normal job title for that day." },
      { type: "feature", description: "Cross-trained shifts display in white with a purple glow animation to visually distinguish them on the schedule." },
      { type: "feature", description: "The cross-trained role name is shown below the shift time in purple italic text." },
      { type: "improvement", description: "eCommerce Director (ECOMDIR) is now Level 3, eCommerce Assistant (EASSIS) is Level 2, and eCommerce Lead (ECMCOMLD) is Level 1 in the attendance and coaching permission hierarchy." },
    ],
  },
  {
    version: "1.37.0",
    date: "2026-03-26",
    title: "eCommerce Location & Position Support",
    changes: [
      { type: "feature", description: "Added support for 12 eCommerce position codes: Director, Commerce Lead, Assistant, Sales Lister, Shipper, Computer/Tech, Junior Seller, Junior Sorter, QC Specialist, Coordinator, Custodian, and Operations Assistant." },
      { type: "feature", description: "eCommerce employees now appear in the Employees page with proper grouping and on the Schedule page with distinct color coding per role." },
      { type: "improvement", description: "The eCommerce location is now fully visible across all pages including Schedule, Employees, Locations, and Roster views." },
    ],
  },
  {
    version: "1.36.0",
    date: "2026-03-26",
    title: "Leadership Shift Preference Enforcement",
    changes: [
      { type: "fix", description: "Leadership scheduling now respects morning_only and evening_only shift preferences across all passes. Previously, managers with shift preferences could be assigned opener or closer slots that conflicted with their preference setting." },
      { type: "improvement", description: "All leadership passes (Pass 1 primary coverage, Pass 2 gap filling and opposite slots, Pass 3/4 fallbacks, and the self-correction pass) now check each manager's shift preference before assigning them to a slot. Morning-only managers will only be assigned opener shifts, and evening-only managers will only be assigned closer shifts." },
    ],
  },
  {
    version: "1.35.0",
    date: "2026-03-26",
    title: "Leadership Scheduling Fixes for Small Manager Pools",
    changes: [
      { type: "fix", description: "Fixed a bug where the scheduler would leave days completely uncovered when there were fewer than 4 managers. Team leads can now fill opener/closer slots as a last resort if no store manager or assistant manager is available for a given day." },
      { type: "fix", description: "The scheduler no longer wastes higher-tier manager capacity on opposite-slot or mid shifts when other days still lack primary coverage. Opposite and mid slots are only filled with higher-tier staff after every day has at least one manager." },
      { type: "fix", description: "Random off days for managers are now automatically overridden in Pass 1 and Pass 2 when no higher-tier manager would otherwise be available for a day. Coverage always takes priority over schedule variety." },
      { type: "fix", description: "Fixed-shift employees are now properly capped by their maximum weekly hours. Previously, the pre-pass only checked days-per-week limits, allowing an employee with a 29-hour max to be scheduled for 40 hours." },
      { type: "fix", description: "Team leads and higher-tier managers no longer receive mid shifts until every day of the week has both an opener and closer. Previously, mid shifts consumed day quotas early, leaving later days without critical coverage." },
      { type: "feature", description: "Day-specific shift overrides: set exact start and end times for individual days per employee (e.g., 'Wednesday 10:00–18:30'). The scheduler uses these times on the specified days, overriding all other shift preference settings." },
      { type: "feature", description: "Added a self-correction pass at the end of leadership scheduling. After all regular passes, the scheduler scans for any remaining gaps and actively fills them by relaxing constraints: first overriding max-days limits, then trying short shifts (5.5 hours) for managers near their weekly hour cap." },
    ],
  },
  {
    version: "1.34.0",
    date: "2026-03-23",
    title: "Scheduler Overhaul, Shift Preferences, FTE Roster & Station Removal",
    changes: [
      { type: "feature", description: "Shift Preference — employees can be set to 'Morning only', 'Evening only', 'Fixed shift', or 'No preference'. The auto-scheduler enforces these as hard constraints. Fixed-shift employees get their exact configured start/end times every working day." },
      { type: "feature", description: "FTE tracking on the Roster page. Managers set a Target FTE per job title; Actual FTE is auto-calculated from each employee's max weekly hours (hours ÷ 40). A consolidated 'All Locations' tab shows Target FTE, Actual FTE, Variance, and Vacancy Rate across every store." },
      { type: "fix", description: "Fixed a critical leadership scheduling bug where two team leads could be scheduled as openers with no closer. Team leads can now only open if a higher-tier manager (store manager or assistant manager) is confirmed to close that day, and vice versa. This constraint is enforced across all scheduling passes." },
      { type: "fix", description: "Fixed-shift managers and team leads are now correctly recognized by the coverage tracker. The scheduler reads each fixed-shift employee's actual start time to determine opener (≤9am), mid (10am), or closer (≥11am), and places the complementary higher-tier manager in the opposite slot automatically." },
      { type: "fix", description: "Production staffing (apparel processors and donation pricers) now distributes evenly across all 7 days using a Saturday-first round-robin. Previously, the scheduler filled Sunday first, then Monday, etc., which left Friday and Saturday short." },
      { type: "fix", description: "FTE Report now shows actual FTE for every job code present at the location — no targets required. Previously blank unless targets had been saved." },
      { type: "fix", description: "Fixed a bug where saving FTE targets more than once would silently discard the updated value." },
      { type: "improvement", description: "Station slot limits for apparel processing and donation pricing have been removed. The scheduler distributes all available production staff evenly across the week with no cap. The Locations page now only shows the weekly hours budget." },
      { type: "improvement", description: "Higher-tier managers are prioritized for days where team leads already have shifts. Random days off for store/assistant managers now avoid team-lead-dependent days." },
      { type: "improvement", description: "Extended slot-aware scheduling to greeters and cashiers. The scheduler reads each fixed-shift employee's actual start time to determine which slot they fill, then seeks the correct complementary coverage." },
      { type: "improvement", description: "Cashier opener/closer split now accounts for fixed-shift cashiers, subtracting confirmed fixed openers/closers from the targets before splitting the remainder." },
    ],
  },
  {
    version: "1.17.0",
    date: "2026-03-18",
    title: "Roster Targets",
    changes: [
      { type: "feature", description: "Added a new 'Roster Targets' page (visible to managers and admins) that lets managers set expected headcount per job title for each location." },
      { type: "feature", description: "Roster report tab shows a side-by-side comparison of target vs. actual active employee count per job title, with color-coded variance indicators and overall summary cards." },
    ],
  },
  {
    version: "1.16.4",
    date: "2026-03-18",
    title: "Rescinded Time-Off Detection",
    changes: [
      { type: "improvement", description: "The UKG time clock sync now performs a delete-then-insert for each date window rather than a pure upsert. This means time-off entries that are rescinded and removed in UKG will also be removed from the local database on the next sync run." },
      { type: "improvement", description: "The raw UKG Status field is now captured and stored on every time clock record (both aggregated entries and individual punches). All unique Status values seen per sync run are logged, which will allow mapping the exact values UKG uses for active vs. voided entries over time." },
    ],
  },
  {
    version: "1.16.2",
    date: "2026-03-18",
    title: "Closer Recognition Expanded to All Days",
    changes: [
      { type: "improvement", description: "Managers ending at 8:30 PM on weekdays now count as closing managers, regardless of shift start time." },
      { type: "improvement", description: "Donor greeters ending at 8:00 PM or 8:30 PM on weekdays now count as closing greeters." },
    ],
  },
  {
    version: "1.16.1",
    date: "2026-03-18",
    title: "Sunday Closer Recognition Improvements",
    changes: [
      { type: "improvement", description: "Managers scheduled until 7:30 PM on Sunday now correctly count as closing managers (previously required an exact start time match to qualify)." },
      { type: "improvement", description: "Donor greeters scheduled until 7:00 PM or 7:30 PM on Sunday now correctly count as closing greeters." },
    ],
  },
  {
    version: "1.16.0",
    date: "2026-03-18",
    title: "Location Sync Bug Fix & Closer Detection",
    changes: [
      { type: "fix", description: "Employee locations are no longer erased during UKG sync. Previously, when UKG's OrgLevel1 API returned no location for an employee (due to missing OrgLevel1Id or a partial API response), the sync would overwrite the employee's database location with null — causing them to disappear from all location-filtered schedule views. Now, if UKG provides no location data for an existing employee, the value already stored in the database is preserved." },
      { type: "improvement", description: "Cashiers ending at 7:00 or 7:30 PM on Sunday, or 8:00 or 8:30 PM on other days, now count as closing cashiers regardless of shift start time." },
    ],
  },
  {
    version: "1.15.0",
    date: "2026-03-16",
    title: "Attendance Fixes & Schedule Improvements",
    changes: [
      { type: "fix", description: "Consecutive absence records now correctly excluded from occurrence totals - the 'consecutive sickness' flag was not being saved to the database, causing these absences to count against employees despite the UI indicating otherwise" },
      { type: "improvement", description: "Opening shift thresholds updated for cashiers and donor greeters: Sunday shifts starting at or before 11:00 AM now count as openers (previously 10:00 AM), and Mon–Sat shifts starting at or before 9:00 AM now count as openers (previously 8:45 AM)" },
      { type: "improvement", description: "Exported PDF schedule now shows a separator line between each job title group for easier reading" },
      { type: "security", description: "Bumped rollup build dependency from 4.53.5 to 4.59.0 to address security advisory" },
    ],
  },
  {
    version: "1.14.1",
    date: "2026-03-10",
    title: "Schedule Performance Improvements",
    changes: [
      { type: "improvement", description: "Added database indexes on shifts table (start_time, employee_id, composite) for faster schedule queries" },
      { type: "improvement", description: "Added database indexes on employees table (is_active, email, location) for faster lookups" },
      { type: "improvement", description: "Schedule page now shows previous week's data while loading the new week, eliminating blank loading flashes when switching weeks" },
      { type: "improvement", description: "Removed redundant client-side data validation on shift fetches for faster rendering" },
      { type: "improvement", description: "Employee, location, and settings data now cached for 5 minutes to avoid unnecessary re-fetches during navigation" },
    ],
  },
  {
    version: "1.14.0",
    date: "2026-03-10",
    title: "Inactive Employee Visibility & Sales Floor",
    changes: [
      { type: "feature", description: "Active/inactive employee toggle on the Employees page - managers and admins can switch to view inactive employees" },
      { type: "feature", description: "Active/inactive employee toggle on the Coaching page - managers and admins can switch to view and search coaching logs for inactive employees" },
      { type: "feature", description: "Added SLSFLR (Sales Floor Associate) as a recognized retail job code - scheduled following the same pattern as Cashiers" },
      { type: "fix", description: "Template save now respects the selected location filter - previously saved shifts from all locations regardless of which store was selected" },
      { type: "fix", description: "Template apply now only creates shifts for employees at the selected location - previously inserted shifts for all locations in the template, causing duplicates on repeated applies" },
      { type: "fix", description: "Added duplicate shift prevention to template apply and copy-to-next-week - identical shifts for the same employee are now automatically deduplicated" },
    ],
  },
  {
    version: "1.13.1",
    date: "2026-03-02",
    title: "Security Hardening",
    changes: [
      { type: "security", description: "All API endpoints now require authentication - previously 20+ endpoints for employees, shifts, time-off, schedule generation, and weather were publicly accessible without login" },
      { type: "security", description: "Write endpoints now enforce role-based access - employee creation requires manager, employee deletion requires admin, shift and schedule operations require manager" },
      { type: "security", description: "Shift trade respond now verifies caller identity - only the designated trade responder (Employee B) can accept or decline a trade" },
      { type: "security", description: "Shift trade cancel now checks ownership - only the trade requester or a manager can cancel a pending trade" },
      { type: "security", description: "Notification mark-as-read now checks ownership - users can only mark their own notifications as read" },
      { type: "security", description: "UKG integration endpoints (status, stores, employees) now require authentication; sync requires admin" },
      { type: "security", description: "Legacy auth bypass removed - a dev-mode authentication function that skipped auth when SSO was unconfigured has been retired to prevent accidental use" },
      { type: "security", description: "Role requirements, time-off requests, and PAL entries endpoints now properly gated by role" },
    ],
  },
  {
    version: "1.13.0",
    date: "2026-02-26",
    title: "Scheduling Fixes, Validation & Policy Updates",
    changes: [
      { type: "feature", description: "Missed punches section on the Variance Report - flags employees with fewer clock punches than expected (4 for shifts over 5 hours, 2 for shorter shifts)" },
      { type: "feature", description: "Multiple HR notification emails - the HR email field now accepts comma-separated addresses so alerts go to multiple recipients" },
      { type: "fix", description: "Schedule templates now correctly capture all Saturday shifts - closing shifts that ended after 7 PM ET were previously excluded when saving templates" },
      { type: "fix", description: "Template apply and copy-to-next-week now use Eastern Time for accurate day and hour placement, preventing shifts from drifting across DST boundaries" },
      { type: "fix", description: "Store hours total now excludes hidden employees so the budget display matches what's shown on the schedule" },
      { type: "fix", description: "Store hours total now accounts for unpaid lunch breaks (subtracts 30 minutes for shifts 6+ hours)" },
      { type: "fix", description: "Schedule validator now works for managers - previously only admins could see validation errors due to a settings access restriction" },
      { type: "improvement", description: "Occurrence adjustment limit changed from 2 to 1 per calendar year to match company policy" },
    ],
  },
  {
    version: "1.12.0",
    date: "2026-02-25",
    title: "Access Controls, PDF Exports & Status Filters",
    changes: [
      { type: "security", description: "Same-level peer restriction - Assistant Managers can no longer view each other's coaching logs or attendance records, and Team Leads can no longer view each other's records" },
      { type: "security", description: "Occurrence Report now enforces hierarchical access - managers below Store Manager level only see employees below their rank" },
      { type: "feature", description: "Active/inactive employee toggle on the Occurrence Report page - managers and admins can switch between viewing active and inactive employees" },
      { type: "feature", description: "Active/inactive employee toggle on the Attendance page - managers and admins can switch the employee dropdown to show inactive employees" },
      { type: "feature", description: "PDF export for occurrence records - download a formatted PDF of an employee's occurrences, adjustments, and corrective actions from the Attendance page" },
      { type: "feature", description: "PDF export for coaching logs - download a formatted PDF of all coaching logs matching the current filters" },
      { type: "improvement", description: "Attendance page employee dropdown now filtered by hierarchical access - managers only see employees they have permission to manage" },
    ],
  },
  {
    version: "1.11.0",
    date: "2026-02-13",
    title: "Mobile Schedule View & Permissions Update",
    changes: [
      { type: "feature", description: "Mobile-friendly schedule view - on phones the schedule now defaults to showing the current day instead of the entire week, with a day selector strip to quickly switch between days" },
      { type: "improvement", description: "Mobile day navigation arrows and tappable day buttons for easy single-day browsing on small screens" },
      { type: "improvement", description: "Today is visually highlighted in the mobile day selector so you can always spot it" },
      { type: "improvement", description: "Mobile day view automatically resets to today when viewing the current week, or to Sunday for past/future weeks" },
      { type: "improvement", description: "Mobile daily hours total now includes PAL and UTO hours for accurate totals matching the desktop view" },
      { type: "security", description: "Store Managers can now see and manage all employees at their assigned store locations, including other managers" },
      { type: "security", description: "Hierarchical access control applied to all occurrence endpoints - managers can only view and manage employees below their job title level (except Store Managers who see all at their locations)" },
      { type: "fix", description: "Fixed adjustment retraction endpoint missing access control check - managers could previously retract adjustments for employees outside their permitted hierarchy" },
    ],
  },
  {
    version: "1.10.5",
    date: "2026-02-12",
    title: "Employee Page & Coaching Improvements",
    changes: [
      { type: "improvement", description: "Employees page now groups employees by job title with collapsible sections, matching the schedule's priority ordering" },
      { type: "improvement", description: "Rebalanced column widths on the Employees page so Days Off and other fields no longer get cut off" },
      { type: "feature", description: "Location filter added to Coaching Logs page for managers overseeing multiple stores" },
      { type: "improvement", description: "Coaching log employee dropdowns and filters respect the selected location" },
      { type: "improvement", description: "Navigation reorganized with section headers: Scheduling, Development, Configuration, Reports, Admin" },
      { type: "improvement", description: "Microsoft SSO now shows account picker instead of auto-selecting a logged-in account" },
    ],
  },
  {
    version: "1.10.0",
    date: "2026-02-12",
    title: "Coaching Logs",
    changes: [
      { type: "feature", description: "Coaching Logs - managers can document feedback conversations with team members including reason, action taken, and employee response" },
      { type: "feature", description: "Hierarchical access control for coaching logs - Store Managers see all team members, Assistant Managers see Team Leads and below, Team Leads see regular staff only" },
      { type: "feature", description: "Employees can view their own coaching history through the Coaching page" },
      { type: "improvement", description: "Coaching categories include Attendance, Safety, Training, Recognition, and Coaching for organized tracking" },
    ],
  },
  {
    version: "1.9.0",
    date: "2026-02-11",
    title: "Manager Reports",
    changes: [
      { type: "feature", description: "Occurrence Report - view employees and their total attendance points by location with threshold highlighting (Warning at 5+, Final Warning at 7+, Termination at 8+)" },
      { type: "feature", description: "Variance Report - track early clock-ins, late clock-outs, and extended lunch breaks by comparing scheduled shifts against actual UKG punch data" },
      { type: "feature", description: "Reports section added to sidebar navigation for managers and admins" },
      { type: "improvement", description: "UKG sync now stores individual punch records for detailed variance analysis including lunch gap detection" },
      { type: "improvement", description: "Schedule view now displays first clock-in and last clock-out times alongside existing hours totals" },
    ],
  },
  {
    version: "1.8.6",
    date: "2026-02-11",
    title: "Admin Tools & Backend Improvements",
    changes: [
      { type: "feature", description: "UKG API credentials can now be configured directly from the Settings page by admins, replacing manual environment variable setup" },
      { type: "feature", description: "UKG diagnostics panel added for monitoring sync health, API connectivity, and performance metrics" },
      { type: "feature", description: "Email logging system tracks all outgoing emails for admin review, providing visibility into notification delivery" },
      { type: "improvement", description: "Backend routes refactored into focused modules for better maintainability - UKG, occurrences, and shift trades each have dedicated route files" },
    ],
  },
  {
    version: "1.8.5",
    date: "2026-02-07",
    title: "Validation & Export Fixes",
    changes: [
      { type: "improvement", description: "Opening cashier validation relaxed - cashiers starting at or before 8:45 AM now count as openers instead of requiring exact 8:00 AM start" },
      { type: "improvement", description: "Opening donor door attendant validation relaxed - attendants starting at or before 8:45 AM now count as openers" },
      { type: "fix", description: "PDF export now displays correct shift times in Eastern Time - previously showed times shifted by the browser's local timezone offset" },
    ],
  },
  {
    version: "1.8.1",
    date: "2026-02-06",
    title: "Scheduling & Export Improvements",
    changes: [
      { type: "improvement", description: "Production scheduling redesigned - Phase 1 now fills ALL station slots every day up to the configured limit before Phase 2 adds extra shifts on Friday and Saturday" },
      { type: "improvement", description: "Sunday opener shifts now start at 10:00 AM by default, with flexible validation - any shift starting at 10am or before counts as an opener on Sundays" },
      { type: "improvement", description: "Schedule view now shows total paid hours per position group instead of shift count" },
      { type: "improvement", description: "Exported PDF schedules now display PAL (Paid Annual Leave) days and include PAL hours in weekly totals" },
      { type: "improvement", description: "Settings page reorganized with role-based visibility - viewers see only notification preferences" },
      { type: "fix", description: "Schedule no longer loses selected week and location on page refresh - selections persist in URL" },
    ],
  },
  {
    version: "1.8.0",
    date: "2026-02-06",
    title: "Shift Trading",
    changes: [
      { type: "feature", description: "Shift trading - employees can request to swap shifts with coworkers who share the same job title" },
      { type: "feature", description: "Two-step trade approval - peer must accept the trade first, then a manager approves before shifts are swapped" },
      { type: "feature", description: "Trade notifications - in-app notification bell shows trade requests, approvals, and declines with tabs for Trades and Attendance alerts" },
      { type: "feature", description: "Email notifications sent at each trade step (request, peer response, manager decision) via Outlook integration" },
      { type: "feature", description: "Shift Trades page - dedicated page to view, filter, and manage all trade requests with manager approval queue" },
      { type: "feature", description: "Visual trade indicators - tradeable shifts on the schedule glow for viewers with matching job titles" },
      { type: "improvement", description: "Automatic conflict detection prevents overlapping trades and self-trading" },
    ],
  },
  {
    version: "1.7.0",
    date: "2026-02-06",
    title: "Schedule Variety & Daily Coverage",
    changes: [
      { type: "feature", description: "Daily Coverage Gantt chart - click any day header to visualize all shifts for that day on a 7am-8pm timeline with position-colored bars" },
      { type: "improvement", description: "Schedule variety - each generation now produces a different valid schedule by randomizing shift type assignments and employee selection across all phases" },
      { type: "improvement", description: "Leadership scheduling variety - managers and team leads are now distributed across different days and shift types each generation instead of always landing on the same days" },
      { type: "improvement", description: "Team lead slot assignment randomized - team leads now randomly fill opener, closer, or mid slots instead of always filling in a fixed order" },
      { type: "improvement", description: "Mid-shift variety for managers - mid shifts now randomly vary between 9am, 10am, and 11am start times" },
      { type: "fix", description: "Fixed manager day repetition - managers no longer get assigned to the same days every time the schedule is generated" },
      { type: "feature", description: "Clickable employee names - click any employee name in the schedule to jump to their configuration page, pre-filtered to that employee" },
    ],
  },
  {
    version: "1.6.1",
    date: "2026-02-05",
    title: "Scheduler Improvements",
    changes: [
      { type: "improvement", description: "Two-phase production scheduling - ensures minimum coverage for all days before prioritizing busy days (Fri/Sat/Sun)" },
      { type: "improvement", description: "Fixed production day ordering - Phase 1 uses fixed order to guarantee all days get minimum coverage" },
      { type: "improvement", description: "Streamlined schedule generation - removed AI scheduler in favor of optimized rule-based scheduler" },
      { type: "feature", description: "Dark mode support with persistent user preference" },
      { type: "improvement", description: "Employee info in schedule now shows configured max hours and status (e.g., '24h max, PT')" },
    ],
  },
  {
    version: "1.6.0",
    date: "2026-02-04",
    title: "Production Controls & Manager Tools",
    changes: [
      { type: "feature", description: "Added production station limits per location - configure maximum Apparel Processors and Donation Pricers per day" },
      { type: "feature", description: "Scheduler respects production station limits when generating schedules" },
      { type: "feature", description: "Schedule validator warns when daily station limits are exceeded" },
      { type: "feature", description: "Store-specific manager notifications - occurrence threshold alerts now go to managers assigned to that store" },
      { type: "feature", description: "Managers can now access the Locations page to view and edit settings for their assigned stores" },
      { type: "feature", description: "Managers can now use quick shift presets when adding shifts" },
      { type: "feature", description: "Added 'Days Off' column to employee list showing non-working days at a glance" },
      { type: "feature", description: "Inline editable Max Hours field in employee list for quick adjustments (0-40)" },
      { type: "improvement", description: "HR email notifications fall back to global HR email if no store managers are configured" },
      { type: "fix", description: "Schedule validator now correctly shows issues only for the currently selected week" },
    ],
  },
  {
    version: "1.5.0",
    date: "2026-02-02",
    title: "Scheduling Flexibility & Session Management",
    changes: [
      { type: "feature", description: "Added tiered leadership scheduling - Store Manager, Assistant Manager, and Team Leads can flexibly cover leadership requirements" },
      { type: "feature", description: "Added location enable/disable toggle to control which stores appear in scheduling" },
      { type: "feature", description: "Hold Ctrl/Cmd while dragging shifts to copy instead of move" },
      { type: "feature", description: "Schedule generation now fills gaps around existing shifts instead of overwriting" },
      { type: "improvement", description: "Randomized manager shift assignments - store managers now get variety in opener/closer/mid shifts" },
      { type: "improvement", description: "Randomized day processing order to spread manager coverage across all days of the week" },
      { type: "improvement", description: "Team leads now only scheduled when a store manager or assistant manager is also on the schedule" },
      { type: "improvement", description: "Minimum staffing requirements: at least 1 donation pricer and 2 apparel processors per day" },
      { type: "improvement", description: "Enhanced notification bell with prominent placement and label in sidebar" },
      { type: "improvement", description: "Automatic redirect to login when session expires after server restart" },
      { type: "improvement", description: "Updated favicon to official Goodwill Smiling G logo" },
      { type: "fix", description: "Fixed schedule auto-generation failing for all stores" },
    ],
  },
  {
    version: "1.4.0",
    date: "2026-02-02",
    title: "Enhanced User Experience",
    changes: [
      { type: "improvement", description: "Added optimistic updates for shift drag-and-drop for instant UI feedback" },
      { type: "improvement", description: "Improved error messages when editing employees to show specific issues" },
      { type: "feature", description: "Added changelog page for users to track app updates" },
      { type: "fix", description: "Fixed part-time days dropdown to include options 1-5 instead of just 4-5" },
      { type: "fix", description: "Fixed Total Allocated Hours to only count displayed stores on Locations page" },
    ],
  },
  {
    version: "1.3.0",
    date: "2026-01-28",
    title: "HR Notifications & Email Integration",
    changes: [
      { type: "feature", description: "Added automated HR email notifications when employees cross occurrence thresholds (5, 7, 8 points)" },
      { type: "feature", description: "Integrated Azure AD app registration for sending emails from shared HR mailbox" },
      { type: "improvement", description: "Smart threshold detection prevents duplicate notification emails" },
      { type: "fix", description: "Fixed SSO login loop by adding proxy trust and explicit session saving" },
    ],
  },
  {
    version: "1.2.0",
    date: "2026-01-20",
    title: "Occurrence Management Enhancements",
    changes: [
      { type: "feature", description: "Added corrective action tracking with progressive discipline sequence (warning, final warning, termination)" },
      { type: "feature", description: "Added PDF document attachments for occurrence records via Object Storage" },
      { type: "feature", description: "Added occurrence alerts with threshold indicators in notification bell" },
      { type: "improvement", description: "Occurrence tally calculation now uses rolling 12-month window" },
      { type: "feature", description: "Added adjustment occurrences for correcting attendance records" },
    ],
  },
  {
    version: "1.1.0",
    date: "2026-01-12",
    title: "Scheduling Intelligence",
    changes: [
      { type: "feature", description: "Added AI-powered auto-generate schedule based on availability and role requirements" },
      { type: "feature", description: "Added schedule validation with warnings for max hours, clopening, and consecutive days" },
      { type: "feature", description: "Added schedule templates - save and apply schedule patterns" },
      { type: "feature", description: "Added copy schedule to next week functionality" },
      { type: "feature", description: "Added weather forecasts display on scheduling page" },
      { type: "improvement", description: "Added holiday detection for Easter, Thanksgiving, and Christmas" },
      { type: "feature", description: "Added paid holiday hour reduction for full-time employees" },
    ],
  },
  {
    version: "1.0.0",
    date: "2026-01-05",
    title: "Initial Release",
    changes: [
      { type: "feature", description: "Weekly calendar view for employee scheduling" },
      { type: "feature", description: "UKG Workforce Management integration for employee and time clock sync" },
      { type: "feature", description: "Microsoft 365 SSO authentication with Azure AD" },
      { type: "feature", description: "Role-based access control (Admin, Manager, Viewer)" },
      { type: "feature", description: "Location-based manager restrictions" },
      { type: "feature", description: "Time-off request management" },
      { type: "feature", description: "Employee management with retail job codes" },
      { type: "feature", description: "Attendance tracking with occurrence points system" },
      { type: "feature", description: "Schedule publishing controls for viewer visibility" },
      { type: "feature", description: "Hide from schedule option for terminated employees pending UKG processing" },
      { type: "feature", description: "Labor allocation configuration for store hours distribution" },
      { type: "feature", description: "PDF schedule export with Goodwill branding" },
    ],
  },
];
