export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  changes: {
    type: "feature" | "improvement" | "fix" | "security";
    description: string;
  }[];
}

export const APP_VERSION = "1.21.0";

export const changelog: ChangelogEntry[] = [
  {
    version: "1.21.0",
    date: "2026-03-23",
    title: "Employee-Driven Actual FTE",
    changes: [
      { type: "improvement", description: "Actual FTE is now calculated directly from each employee's configured max weekly hours (max hours ÷ 40), not a manual rate. A 40h employee = 1.00 FTE, a 29h employee = 0.725 FTE, etc." },
      { type: "improvement", description: "Targets tab simplified to a single input per job title: Target FTE. No manual FTE rate entry needed." },
    ],
  },
  {
    version: "1.20.0",
    date: "2026-03-23",
    title: "FTE-Only Roster Mode",
    changes: [
      { type: "improvement", description: "Roster is now fully FTE-centric — no headcount columns. Targets tab has two inputs per job: Target FTE (the staffing goal in FTE units) and FTE Rate per employee (e.g. 0.73 for 29h, 1.00 for 40h)." },
      { type: "improvement", description: "FTE Report and All Locations tabs now show only FTE data: Target FTE, Actual FTE, FTE Variance, and Vacancy Rate. Headcount columns removed throughout." },
    ],
  },
  {
    version: "1.19.0",
    date: "2026-03-23",
    title: "Consolidated Roster Report",
    changes: [
      { type: "feature", description: "Added a new 'All Locations' tab on the Roster page showing every location in a single view with Target, Actual, Variance, Vacancy Rate, and FTE columns." },
      { type: "feature", description: "Vacancy Rate per location is shown as a percentage of unfilled positions relative to target headcount, color-coded red (understaffed), yellow (near target), or green (on track). A grand total row summarizes across all locations." },
      { type: "feature", description: "Summary cards at the top of the Consolidated tab show overall Total Target, Total Active, Overall Vacancy Rate (with position count), and total FTE (when configured)." },
    ],
  },
  {
    version: "1.18.0",
    date: "2026-03-23",
    title: "FTE Tracking on Roster",
    changes: [
      { type: "feature", description: "Managers can now enter an FTE (Full Time Equivalent) value per job title on the Roster Targets page — e.g. 1.00 for a 40-hour role, 0.73 for a 29-hour role." },
      { type: "feature", description: "The Roster Report now shows Target FTE and Actual FTE columns per job title, calculated as headcount × FTE value. Summary cards for total Target FTE, Actual FTE, and FTE Variance appear when FTE values are configured." },
    ],
  },
  {
    version: "1.17.0",
    date: "2026-03-18",
    title: "Roster Targets",
    changes: [
      { type: "feature", description: "Added a new 'Roster Targets' page (visible to managers and admins) that lets managers set expected headcount per job title for each location." },
      { type: "feature", description: "Roster report tab shows a side-by-side comparison of target vs. actual active employee count per job title, with color-coded variance indicators and overall summary cards." },
    ],
  },
  {
    version: "1.16.4",
    date: "2026-03-18",
    title: "Rescinded Time-Off Detection",
    changes: [
      { type: "improvement", description: "The UKG time clock sync now performs a delete-then-insert for each date window rather than a pure upsert. This means time-off entries that are rescinded and removed in UKG will also be removed from the local database on the next sync run." },
      { type: "improvement", description: "The raw UKG Status field is now captured and stored on every time clock record (both aggregated entries and individual punches). All unique Status values seen per sync run are logged, which will allow mapping the exact values UKG uses for active vs. voided entries over time." },
    ],
  },
  {
    version: "1.16.2",
    date: "2026-03-18",
    title: "Closer Recognition Expanded to All Days",
    changes: [
      { type: "improvement", description: "Managers ending at 8:30 PM on weekdays now count as closing managers, regardless of shift start time." },
      { type: "improvement", description: "Donor greeters ending at 8:00 PM or 8:30 PM on weekdays now count as closing greeters." },
    ],
  },
  {
    version: "1.16.1",
    date: "2026-03-18",
    title: "Sunday Closer Recognition Improvements",
    changes: [
      { type: "improvement", description: "Managers scheduled until 7:30 PM on Sunday now correctly count as closing managers (previously required an exact start time match to qualify)." },
      { type: "improvement", description: "Donor greeters scheduled until 7:00 PM or 7:30 PM on Sunday now correctly count as closing greeters." },
    ],
  },
  {
    version: "1.16.0",
    date: "2026-03-18",
    title: "Location Sync Bug Fix & Closer Detection",
    changes: [
      { type: "fix", description: "Employee locations are no longer erased during UKG sync. Previously, when UKG's OrgLevel1 API returned no location for an employee (due to missing OrgLevel1Id or a partial API response), the sync would overwrite the employee's database location with null — causing them to disappear from all location-filtered schedule views. Now, if UKG provides no location data for an existing employee, the value already stored in the database is preserved." },
      { type: "improvement", description: "Cashiers ending at 7:00 or 7:30 PM on Sunday, or 8:00 or 8:30 PM on other days, now count as closing cashiers regardless of shift start time." },
    ],
  },
  {
    version: "1.15.0",
    date: "2026-03-16",
    title: "Attendance Fixes & Schedule Improvements",
    changes: [
      { type: "fix", description: "Consecutive absence records now correctly excluded from occurrence totals - the 'consecutive sickness' flag was not being saved to the database, causing these absences to count against employees despite the UI indicating otherwise" },
      { type: "improvement", description: "Opening shift thresholds updated for cashiers and donor greeters: Sunday shifts starting at or before 11:00 AM now count as openers (previously 10:00 AM), and Mon–Sat shifts starting at or before 9:00 AM now count as openers (previously 8:45 AM)" },
      { type: "improvement", description: "Exported PDF schedule now shows a separator line between each job title group for easier reading" },
      { type: "security", description: "Bumped rollup build dependency from 4.53.5 to 4.59.0 to address security advisory" },
    ],
  },
  {
    version: "1.14.1",
    date: "2026-03-10",
    title: "Schedule Performance Improvements",
    changes: [
      { type: "improvement", description: "Added database indexes on shifts table (start_time, employee_id, composite) for faster schedule queries" },
      { type: "improvement", description: "Added database indexes on employees table (is_active, email, location) for faster lookups" },
      { type: "improvement", description: "Schedule page now shows previous week's data while loading the new week, eliminating blank loading flashes when switching weeks" },
      { type: "improvement", description: "Removed redundant client-side data validation on shift fetches for faster rendering" },
      { type: "improvement", description: "Employee, location, and settings data now cached for 5 minutes to avoid unnecessary re-fetches during navigation" },
    ],
  },
  {
    version: "1.14.0",
    date: "2026-03-10",
    title: "Inactive Employee Visibility & Sales Floor",
    changes: [
      { type: "feature", description: "Active/inactive employee toggle on the Employees page - managers and admins can switch to view inactive employees" },
      { type: "feature", description: "Active/inactive employee toggle on the Coaching page - managers and admins can switch to view and search coaching logs for inactive employees" },
      { type: "feature", description: "Added SLSFLR (Sales Floor Associate) as a recognized retail job code - scheduled following the same pattern as Cashiers" },
      { type: "fix", description: "Template save now respects the selected location filter - previously saved shifts from all locations regardless of which store was selected" },
      { type: "fix", description: "Template apply now only creates shifts for employees at the selected location - previously inserted shifts for all locations in the template, causing duplicates on repeated applies" },
      { type: "fix", description: "Added duplicate shift prevention to template apply and copy-to-next-week - identical shifts for the same employee are now automatically deduplicated" },
    ],
  },
  {
    version: "1.13.1",
    date: "2026-03-02",
    title: "Security Hardening",
    changes: [
      { type: "security", description: "All API endpoints now require authentication - previously 20+ endpoints for employees, shifts, time-off, schedule generation, and weather were publicly accessible without login" },
      { type: "security", description: "Write endpoints now enforce role-based access - employee creation requires manager, employee deletion requires admin, shift and schedule operations require manager" },
      { type: "security", description: "Shift trade respond now verifies caller identity - only the designated trade responder (Employee B) can accept or decline a trade" },
      { type: "security", description: "Shift trade cancel now checks ownership - only the trade requester or a manager can cancel a pending trade" },
      { type: "security", description: "Notification mark-as-read now checks ownership - users can only mark their own notifications as read" },
      { type: "security", description: "UKG integration endpoints (status, stores, employees) now require authentication; sync requires admin" },
      { type: "security", description: "Legacy auth bypass removed - a dev-mode authentication function that skipped auth when SSO was unconfigured has been retired to prevent accidental use" },
      { type: "security", description: "Role requirements, time-off requests, and PAL entries endpoints now properly gated by role" },
    ],
  },
  {
    version: "1.13.0",
    date: "2026-02-26",
    title: "Scheduling Fixes, Validation & Policy Updates",
    changes: [
      { type: "feature", description: "Missed punches section on the Variance Report - flags employees with fewer clock punches than expected (4 for shifts over 5 hours, 2 for shorter shifts)" },
      { type: "feature", description: "Multiple HR notification emails - the HR email field now accepts comma-separated addresses so alerts go to multiple recipients" },
      { type: "fix", description: "Schedule templates now correctly capture all Saturday shifts - closing shifts that ended after 7 PM ET were previously excluded when saving templates" },
      { type: "fix", description: "Template apply and copy-to-next-week now use Eastern Time for accurate day and hour placement, preventing shifts from drifting across DST boundaries" },
      { type: "fix", description: "Store hours total now excludes hidden employees so the budget display matches what's shown on the schedule" },
      { type: "fix", description: "Store hours total now accounts for unpaid lunch breaks (subtracts 30 minutes for shifts 6+ hours)" },
      { type: "fix", description: "Schedule validator now works for managers - previously only admins could see validation errors due to a settings access restriction" },
      { type: "improvement", description: "Occurrence adjustment limit changed from 2 to 1 per calendar year to match company policy" },
    ],
  },
  {
    version: "1.12.0",
    date: "2026-02-25",
    title: "Access Controls, PDF Exports & Status Filters",
    changes: [
      { type: "security", description: "Same-level peer restriction - Assistant Managers can no longer view each other's coaching logs or attendance records, and Team Leads can no longer view each other's records" },
      { type: "security", description: "Occurrence Report now enforces hierarchical access - managers below Store Manager level only see employees below their rank" },
      { type: "feature", description: "Active/inactive employee toggle on the Occurrence Report page - managers and admins can switch between viewing active and inactive employees" },
      { type: "feature", description: "Active/inactive employee toggle on the Attendance page - managers and admins can switch the employee dropdown to show inactive employees" },
      { type: "feature", description: "PDF export for occurrence records - download a formatted PDF of an employee's occurrences, adjustments, and corrective actions from the Attendance page" },
      { type: "feature", description: "PDF export for coaching logs - download a formatted PDF of all coaching logs matching the current filters" },
      { type: "improvement", description: "Attendance page employee dropdown now filtered by hierarchical access - managers only see employees they have permission to manage" },
    ],
  },
  {
    version: "1.11.0",
    date: "2026-02-13",
    title: "Mobile Schedule View & Permissions Update",
    changes: [
      { type: "feature", description: "Mobile-friendly schedule view - on phones the schedule now defaults to showing the current day instead of the entire week, with a day selector strip to quickly switch between days" },
      { type: "improvement", description: "Mobile day navigation arrows and tappable day buttons for easy single-day browsing on small screens" },
      { type: "improvement", description: "Today is visually highlighted in the mobile day selector so you can always spot it" },
      { type: "improvement", description: "Mobile day view automatically resets to today when viewing the current week, or to Sunday for past/future weeks" },
      { type: "improvement", description: "Mobile daily hours total now includes PAL and UTO hours for accurate totals matching the desktop view" },
      { type: "security", description: "Store Managers can now see and manage all employees at their assigned store locations, including other managers" },
      { type: "security", description: "Hierarchical access control applied to all occurrence endpoints - managers can only view and manage employees below their job title level (except Store Managers who see all at their locations)" },
      { type: "fix", description: "Fixed adjustment retraction endpoint missing access control check - managers could previously retract adjustments for employees outside their permitted hierarchy" },
    ],
  },
  {
    version: "1.10.5",
    date: "2026-02-12",
    title: "Employee Page & Coaching Improvements",
    changes: [
      { type: "improvement", description: "Employees page now groups employees by job title with collapsible sections, matching the schedule's priority ordering" },
      { type: "improvement", description: "Rebalanced column widths on the Employees page so Days Off and other fields no longer get cut off" },
      { type: "feature", description: "Location filter added to Coaching Logs page for managers overseeing multiple stores" },
      { type: "improvement", description: "Coaching log employee dropdowns and filters respect the selected location" },
      { type: "improvement", description: "Navigation reorganized with section headers: Scheduling, Development, Configuration, Reports, Admin" },
      { type: "improvement", description: "Microsoft SSO now shows account picker instead of auto-selecting a logged-in account" },
    ],
  },
  {
    version: "1.10.0",
    date: "2026-02-12",
    title: "Coaching Logs",
    changes: [
      { type: "feature", description: "Coaching Logs - managers can document feedback conversations with team members including reason, action taken, and employee response" },
      { type: "feature", description: "Hierarchical access control for coaching logs - Store Managers see all team members, Assistant Managers see Team Leads and below, Team Leads see regular staff only" },
      { type: "feature", description: "Employees can view their own coaching history through the Coaching page" },
      { type: "improvement", description: "Coaching categories include Attendance, Safety, Training, Recognition, and Coaching for organized tracking" },
    ],
  },
  {
    version: "1.9.0",
    date: "2026-02-11",
    title: "Manager Reports",
    changes: [
      { type: "feature", description: "Occurrence Report - view employees and their total attendance points by location with threshold highlighting (Warning at 5+, Final Warning at 7+, Termination at 8+)" },
      { type: "feature", description: "Variance Report - track early clock-ins, late clock-outs, and extended lunch breaks by comparing scheduled shifts against actual UKG punch data" },
      { type: "feature", description: "Reports section added to sidebar navigation for managers and admins" },
      { type: "improvement", description: "UKG sync now stores individual punch records for detailed variance analysis including lunch gap detection" },
      { type: "improvement", description: "Schedule view now displays first clock-in and last clock-out times alongside existing hours totals" },
    ],
  },
  {
    version: "1.8.6",
    date: "2026-02-11",
    title: "Admin Tools & Backend Improvements",
    changes: [
      { type: "feature", description: "UKG API credentials can now be configured directly from the Settings page by admins, replacing manual environment variable setup" },
      { type: "feature", description: "UKG diagnostics panel added for monitoring sync health, API connectivity, and performance metrics" },
      { type: "feature", description: "Email logging system tracks all outgoing emails for admin review, providing visibility into notification delivery" },
      { type: "improvement", description: "Backend routes refactored into focused modules for better maintainability - UKG, occurrences, and shift trades each have dedicated route files" },
    ],
  },
  {
    version: "1.8.5",
    date: "2026-02-07",
    title: "Validation & Export Fixes",
    changes: [
      { type: "improvement", description: "Opening cashier validation relaxed - cashiers starting at or before 8:45 AM now count as openers instead of requiring exact 8:00 AM start" },
      { type: "improvement", description: "Opening donor door attendant validation relaxed - attendants starting at or before 8:45 AM now count as openers" },
      { type: "fix", description: "PDF export now displays correct shift times in Eastern Time - previously showed times shifted by the browser's local timezone offset" },
    ],
  },
  {
    version: "1.8.1",
    date: "2026-02-06",
    title: "Scheduling & Export Improvements",
    changes: [
      { type: "improvement", description: "Production scheduling redesigned - Phase 1 now fills ALL station slots every day up to the configured limit before Phase 2 adds extra shifts on Friday and Saturday" },
      { type: "improvement", description: "Sunday opener shifts now start at 10:00 AM by default, with flexible validation - any shift starting at 10am or before counts as an opener on Sundays" },
      { type: "improvement", description: "Schedule view now shows total paid hours per position group instead of shift count" },
      { type: "improvement", description: "Exported PDF schedules now display PAL (Paid Annual Leave) days and include PAL hours in weekly totals" },
      { type: "improvement", description: "Settings page reorganized with role-based visibility - viewers see only notification preferences" },
      { type: "fix", description: "Schedule no longer loses selected week and location on page refresh - selections persist in URL" },
    ],
  },
  {
    version: "1.8.0",
    date: "2026-02-06",
    title: "Shift Trading",
    changes: [
      { type: "feature", description: "Shift trading - employees can request to swap shifts with coworkers who share the same job title" },
      { type: "feature", description: "Two-step trade approval - peer must accept the trade first, then a manager approves before shifts are swapped" },
      { type: "feature", description: "Trade notifications - in-app notification bell shows trade requests, approvals, and declines with tabs for Trades and Attendance alerts" },
      { type: "feature", description: "Email notifications sent at each trade step (request, peer response, manager decision) via Outlook integration" },
      { type: "feature", description: "Shift Trades page - dedicated page to view, filter, and manage all trade requests with manager approval queue" },
      { type: "feature", description: "Visual trade indicators - tradeable shifts on the schedule glow for viewers with matching job titles" },
      { type: "improvement", description: "Automatic conflict detection prevents overlapping trades and self-trading" },
    ],
  },
  {
    version: "1.7.0",
    date: "2026-02-06",
    title: "Schedule Variety & Daily Coverage",
    changes: [
      { type: "feature", description: "Daily Coverage Gantt chart - click any day header to visualize all shifts for that day on a 7am-8pm timeline with position-colored bars" },
      { type: "improvement", description: "Schedule variety - each generation now produces a different valid schedule by randomizing shift type assignments and employee selection across all phases" },
      { type: "improvement", description: "Leadership scheduling variety - managers and team leads are now distributed across different days and shift types each generation instead of always landing on the same days" },
      { type: "improvement", description: "Team lead slot assignment randomized - team leads now randomly fill opener, closer, or mid slots instead of always filling in a fixed order" },
      { type: "improvement", description: "Mid-shift variety for managers - mid shifts now randomly vary between 9am, 10am, and 11am start times" },
      { type: "fix", description: "Fixed manager day repetition - managers no longer get assigned to the same days every time the schedule is generated" },
      { type: "feature", description: "Clickable employee names - click any employee name in the schedule to jump to their configuration page, pre-filtered to that employee" },
    ],
  },
  {
    version: "1.6.1",
    date: "2026-02-05",
    title: "Scheduler Improvements",
    changes: [
      { type: "improvement", description: "Two-phase production scheduling - ensures minimum coverage for all days before prioritizing busy days (Fri/Sat/Sun)" },
      { type: "improvement", description: "Fixed production day ordering - Phase 1 uses fixed order to guarantee all days get minimum coverage" },
      { type: "improvement", description: "Streamlined schedule generation - removed AI scheduler in favor of optimized rule-based scheduler" },
      { type: "feature", description: "Dark mode support with persistent user preference" },
      { type: "improvement", description: "Employee info in schedule now shows configured max hours and status (e.g., '24h max, PT')" },
    ],
  },
  {
    version: "1.6.0",
    date: "2026-02-04",
    title: "Production Controls & Manager Tools",
    changes: [
      { type: "feature", description: "Added production station limits per location - configure maximum Apparel Processors and Donation Pricers per day" },
      { type: "feature", description: "Scheduler respects production station limits when generating schedules" },
      { type: "feature", description: "Schedule validator warns when daily station limits are exceeded" },
      { type: "feature", description: "Store-specific manager notifications - occurrence threshold alerts now go to managers assigned to that store" },
      { type: "feature", description: "Managers can now access the Locations page to view and edit settings for their assigned stores" },
      { type: "feature", description: "Managers can now use quick shift presets when adding shifts" },
      { type: "feature", description: "Added 'Days Off' column to employee list showing non-working days at a glance" },
      { type: "feature", description: "Inline editable Max Hours field in employee list for quick adjustments (0-40)" },
      { type: "improvement", description: "HR email notifications fall back to global HR email if no store managers are configured" },
      { type: "fix", description: "Schedule validator now correctly shows issues only for the currently selected week" },
    ],
  },
  {
    version: "1.5.0",
    date: "2026-02-02",
    title: "Scheduling Flexibility & Session Management",
    changes: [
      { type: "feature", description: "Added tiered leadership scheduling - Store Manager, Assistant Manager, and Team Leads can flexibly cover leadership requirements" },
      { type: "feature", description: "Added location enable/disable toggle to control which stores appear in scheduling" },
      { type: "feature", description: "Hold Ctrl/Cmd while dragging shifts to copy instead of move" },
      { type: "feature", description: "Schedule generation now fills gaps around existing shifts instead of overwriting" },
      { type: "improvement", description: "Randomized manager shift assignments - store managers now get variety in opener/closer/mid shifts" },
      { type: "improvement", description: "Randomized day processing order to spread manager coverage across all days of the week" },
      { type: "improvement", description: "Team leads now only scheduled when a store manager or assistant manager is also on the schedule" },
      { type: "improvement", description: "Minimum staffing requirements: at least 1 donation pricer and 2 apparel processors per day" },
      { type: "improvement", description: "Enhanced notification bell with prominent placement and label in sidebar" },
      { type: "improvement", description: "Automatic redirect to login when session expires after server restart" },
      { type: "improvement", description: "Updated favicon to official Goodwill Smiling G logo" },
      { type: "fix", description: "Fixed schedule auto-generation failing for all stores" },
    ],
  },
  {
    version: "1.4.0",
    date: "2026-02-02",
    title: "Enhanced User Experience",
    changes: [
      { type: "improvement", description: "Added optimistic updates for shift drag-and-drop for instant UI feedback" },
      { type: "improvement", description: "Improved error messages when editing employees to show specific issues" },
      { type: "feature", description: "Added changelog page for users to track app updates" },
      { type: "fix", description: "Fixed part-time days dropdown to include options 1-5 instead of just 4-5" },
      { type: "fix", description: "Fixed Total Allocated Hours to only count displayed stores on Locations page" },
    ],
  },
  {
    version: "1.3.0",
    date: "2026-01-28",
    title: "HR Notifications & Email Integration",
    changes: [
      { type: "feature", description: "Added automated HR email notifications when employees cross occurrence thresholds (5, 7, 8 points)" },
      { type: "feature", description: "Integrated Azure AD app registration for sending emails from shared HR mailbox" },
      { type: "improvement", description: "Smart threshold detection prevents duplicate notification emails" },
      { type: "fix", description: "Fixed SSO login loop by adding proxy trust and explicit session saving" },
    ],
  },
  {
    version: "1.2.0",
    date: "2026-01-20",
    title: "Occurrence Management Enhancements",
    changes: [
      { type: "feature", description: "Added corrective action tracking with progressive discipline sequence (warning, final warning, termination)" },
      { type: "feature", description: "Added PDF document attachments for occurrence records via Object Storage" },
      { type: "feature", description: "Added occurrence alerts with threshold indicators in notification bell" },
      { type: "improvement", description: "Occurrence tally calculation now uses rolling 12-month window" },
      { type: "feature", description: "Added adjustment occurrences for correcting attendance records" },
    ],
  },
  {
    version: "1.1.0",
    date: "2026-01-12",
    title: "Scheduling Intelligence",
    changes: [
      { type: "feature", description: "Added AI-powered auto-generate schedule based on availability and role requirements" },
      { type: "feature", description: "Added schedule validation with warnings for max hours, clopening, and consecutive days" },
      { type: "feature", description: "Added schedule templates - save and apply schedule patterns" },
      { type: "feature", description: "Added copy schedule to next week functionality" },
      { type: "feature", description: "Added weather forecasts display on scheduling page" },
      { type: "improvement", description: "Added holiday detection for Easter, Thanksgiving, and Christmas" },
      { type: "feature", description: "Added paid holiday hour reduction for full-time employees" },
    ],
  },
  {
    version: "1.0.0",
    date: "2026-01-05",
    title: "Initial Release",
    changes: [
      { type: "feature", description: "Weekly calendar view for employee scheduling" },
      { type: "feature", description: "UKG Workforce Management integration for employee and time clock sync" },
      { type: "feature", description: "Microsoft 365 SSO authentication with Azure AD" },
      { type: "feature", description: "Role-based access control (Admin, Manager, Viewer)" },
      { type: "feature", description: "Location-based manager restrictions" },
      { type: "feature", description: "Time-off request management" },
      { type: "feature", description: "Employee management with retail job codes" },
      { type: "feature", description: "Attendance tracking with occurrence points system" },
      { type: "feature", description: "Schedule publishing controls for viewer visibility" },
      { type: "feature", description: "Hide from schedule option for terminated employees pending UKG processing" },
      { type: "feature", description: "Labor allocation configuration for store hours distribution" },
      { type: "feature", description: "PDF schedule export with Goodwill branding" },
    ],
  },
];
